---
- hosts: all
  become: yes
  user: root
  roles:
    - crivetimihai.virtualization.lxd
    - crivetimihai.virtualization.docker
  tasks: 
    - name: Require some sw
      apt:
        update_cache: yes
        name: curl 

    - name: Prepare apt for gocd
      shell: |
        echo "deb https://download.gocd.org /" | sudo tee /etc/apt/sources.list.d/gocd.list
        curl https://download.gocd.org/GOCD-GPG-KEY.asc | sudo apt-key add -

    - name: Install server and agent
      apt:
        update_cache: yes
        pkg:
          - go-server
          - go-agent

    - name: Stop server
      shell: /usr/share/go-server/bin/go-server stop

    - name: Run server
      shell: /usr/share/go-server/bin/go-server start

    - name: Go agent start
      shell: /usr/share/go-agent/bin/go-agent start

  
