# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
  

  config.vm.provider "virtualbox" do |v|
	v.memory = 8192
	v.cpus = 4
  end
  config.vm.provision "ansible" do |ansible|
   ansible.playbook = "build_server/install.yml"
  end
  
  config.vm.define "git" do |git|
     git.vm.network :private_network, ip: "192.168.2.3"
  end
end
