# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
  config.vm.provision "ansible" do |ansible|
   ansible.playbook = "git_server/install.yml"
  end

  config.vm.provider "libvirt" do |vb|
     vb.memory = "1024"
  end
  
  config.vm.define "git" do |git|
     git.vm.network :private_network, ip: "192.168.66.15"
  end
end
